experiment_type: 'ssl'
experiment_name: '11_big_mask_size'
run_message: 'run on filtered dataset with larger mask blocks'
ssl_dataset: 'ob007_filter_qual_norm.memmap'

smrt2vec:
  d_model: 128
  n_head: 4
  context: 4096
  n_layers: 4
  vocab_size: 5
  weight_decay: 0.02
  p_mask: 0.15
  epochs: 12
  batch_size: 64
  optimizer: 'AdamW'
  max_lr: 3e-4
  temperature: 0.1
  pct_start: 0.4
  mask_size: 16

data:
  pad_idx: 4 
  token_map:
    'A': 0
    'C': 1
    'G': 2
    'T': 3
    'N': 4
  rc_map:
    'A': 'T'
    'C': 'G'
    'G': 'C'
    'T': 'A'
    'N': 'N'
  kinetics_features: ['fi', 'fp', 'ri', 'rp']
  per_base_tags: ["fi", "ri", "fp", "rp", "sm", "sx", "sa", "fn", "rn"]