model:
  architecture: 'MethylCNNv2'
  params:
    sequence_length: 32
    num_classes: 2
    dropout_p: 0.1
    feature_set: 'hemi'

data:
  token_map:
    'A': 0
    'C': 1
    'G': 2
    'T': 3
    'N': 4
    '[MASK]': 5
    '[PAD]': 6
  restrict_row_groups: 0

training:
  epochs: 10
  batch_size: 8192
  criterion: 
    name: 'BCEWithLogitsLoss'
    params: {}
  optimizer: 
    name: 'AdamW'
    weight_decay: 1.0e-2
    betas: [0.9, 0.999]
    eps: 1.0e-08
    lr: 0.001